### ISSUE TITLE
Could not resolve context values 

### ISSUE THREAD

**Issue by rcoundon** [AndrewGuenther/cdk-fck-nat#296]
Just had a try with cdk-fck-nat and it fails with:
`Could not resolve context values for ami:account=xxxxx:filters.image-type.0=machine:filters.name.0=fck-nat-al2023-*-arm64-ebs:filters.state.0=available:owners.0=568608671756:region=eu-west-2`

I get the same if I try this directly from the docs:
```ts
const natGatewayProvider = new NatInstanceProvider({
    instanceType: InstanceType.of(InstanceClass.T4G, InstanceSize.MICRO),
    machineImage: new LookupMachineImage({
        name: 'fck-nat-al2023-*-arm64-ebs',
        owners: ['568608671756'],
    })
})
```
whereas this works:
```ts
  const natGatewayProvider = new NatInstanceProvider({
    instanceType: InstanceType.of(InstanceClass.T4G, InstanceSize.NANO),
    machineImage: new LookupMachineImage({
      name: 'fck-nat-amzn2-*-arm64-ebs',
      owners: ['568608671756'],
    }),
  });
```
So it appears that there’s a problem with referencing the new machine image
`fck-nat-al2023-*-arm64-ebs` vs `fck-nat-amzn2-*-arm64-ebs`

**Comment by AndrewGuenther** [comment]
Looks like there was a publishing failure for the AMI in some regions, re-deploying it now

**Comment by AndrewGuenther** [comment]
Ugh, I got hit with the new default setting for EC2 that you can't mark AMIs as public. Waiting for that to propagate to all regions now.

**Comment by AndrewGuenther** [comment]
Fixed!

**Comment by rcoundon** [comment]
That's working for me now, thanks for the swift fix.
